# Tensorflow Operations

## TF maths

In [1]:
import tensorflow as tf

2023-07-14 19:01:39.803843: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-14 19:01:39.937467: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-07-14 19:01:39.939318: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-07-14 19:01:41.293634: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


### abs

In [2]:
x = tf.constant([-1, -0.5, 2])
tf.math.abs(x)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 0.5, 2. ], dtype=float32)>

### acos

In [3]:
# acos --> inverse of cos
# y = tf.math.cost(x)
# x = tf.math.acos(y) 
tf.math.acos(x)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([3.1415927, 2.0943952,       nan], dtype=float32)>

### add
 returns element wise addition

In [4]:
y =tf.add(x, [1, 0.5, -1])
z = tf.add(x, 1) # performs broadcasting
y, z

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 1.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0. , 0.5, 3. ], dtype=float32)>)

In [5]:
# alternatively you can use + operator
y = x + [1, 0.5, -1]
z = x + 1
y, z

(<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 1.], dtype=float32)>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([0. , 0.5, 3. ], dtype=float32)>)

**Warning:** If one of the inputs (x or y) is a tensor and the other is a non-tensor, the non-tensor input will adopt (or get casted to) the data type of the tensor input. This can potentially cause unwanted overflow or underflow conversion.

### add_n
- Returns the element-wise sum of a list of tensors.
- All inputs in the list must have the same shape. This op does not broadcast its inputs. If you need broadcasting, use tf.math.add (or the + operator) instead.

In [6]:
tensors = [tf.constant([1,2,3]), tf.constant([4,5,6])]
tf.math.add_n(tensors)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [7]:
try:
    tensors = [tf.constant([1,2,3]), tf.constant([4])]
    tf.math.add_n(tensors)
except Exception as e:
    print(e)
    print("doesnot broadcast")

{{function_node __wrapped__AddN_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Inputs to operation AddN of type AddN must have the same size and shape.  Input 0: [3] != input 1: [1] [Op:AddN]
doesnot broadcast


In [8]:
tensors = tf.constant([[1,2,3], [4,5,6]])
tf.math.add_n(tensors)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [9]:
a = tf.constant([[1,2,3],
                 [4,5,6]])

b = tf.constant([[1,2,3],
                 [4,5,6]])

c = tf.constant([[1,2,3],
                 [4,5,6]])

tf.math.add_n([a, b, c])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 3,  6,  9],
       [12, 15, 18]], dtype=int32)>

### approx_max_k

Returns max k values and their indices of the input operand in an approximate manner.  This op is only optimized on TPU currently.

### argmax
Returns the index with the largest value across axes of a tensor.

In [10]:
a = tf.constant([1, 2, 5, 3, 4])
tf.math.argmax(a).numpy()

2

In [11]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 1]])
print(a.shape)
tf.math.argmax(a, axis=0).numpy() # axis = 0, num of columns will be preserved, argmax along rows

(2, 3)


array([1, 1, 0])

- 1 -> row 1, column 0

- 1 -> row 1, column 1

- 0 -> row 0, column 2 

In [12]:
tf.math.argmax(a, axis=1).numpy() # axis = 1, num of rows will be preserved, argmax along columns

array([2, 1])

- 2 -> column 2, row 0
- 1 -> column 1, row 1

### argmin

Returns the index with the largest value across axes of a tensor.

In [13]:
a = tf.constant([1, 2, 5, 3, 4])
tf.math.argmin(a).numpy()

0

In [14]:
a = tf.constant([[1, 2, 3],
                 [4, 5, 1]])
tf.math.argmin(a, axis=0).numpy()

array([0, 0, 1])

In [15]:
tf.math.argmin(a, axis=1).numpy()

array([0, 2])

### bincount
Counts the number of occurrences of each value in an integer array.

In [16]:
a = tf.constant([1,1,1,1,2,2,2,3,3,0])
tf.math.bincount(a).numpy()

array([1, 4, 3, 2], dtype=int32)

- 0 --> 1
- 1 --> 4
- 2 --> 3
- 3 --> 2

In [17]:
a = tf.constant([10, 10, 10, 2, 2, 2])
tf.math.bincount(a).numpy()

array([0, 0, 3, 0, 0, 0, 0, 0, 0, 0, 3], dtype=int32)

By default bin spacing will be 1 starting from 0 to the max_value of the array

In [18]:
tf.math.bincount(a, minlength=0, maxlength=5).numpy()

array([0, 0, 3, 0, 0], dtype=int32)

- Note that tf.math.bincount() assumes the input tensor contains only non-negative integer values. Negative values or non-integer values will result in an error.

- The tf.math.bincount() function is commonly used for tasks such as computing the frequency of classes in classification problems or analyzing distribution patterns of integer values.

### confusion_matrix

Computes the confusion matrix from predictions and labels.

In [19]:
y_pred = tf.constant([1,1,1,0,0,0])
y_true = tf.constant([0,0,1,0,0,1])

In [20]:
tf.math.confusion_matrix(labels=y_true,
                         predictions=y_pred,
                         num_classes=2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [1, 1]], dtype=int32)>

In [21]:
y_pred = tf.constant([1,2,3,6,0,0])
y_true = tf.constant([1,2,3,1,0,1])

tf.math.confusion_matrix(y_true, y_pred)

<tf.Tensor: shape=(7, 7), dtype=int32, numpy=
array([[1, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 1],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

Note that the possible labels are assumed to be [0, 1, 2, 3, 4, 5, 6], resulting in a 5x5 confusion matrix.

**To do:**
- find out about weight parameter in confuision metrix

### count_nonzero
Computes number of nonzero elements across dimensions of a tensor.

In [25]:
x = tf.constant([[0, 0, 1],
                 [1, 2, 4]])
tf.math.count_nonzero(x, axis=0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 1, 2])>

In [26]:
tf.math.count_nonzero(x, axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 3])>

In [31]:
tf.math.count_nonzero(x, axis=1, keepdims=True)

<tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[1],
       [3]])>

In [32]:
tf.math.count_nonzero(x, axis=[0, 1], keepdims=True)

<tf.Tensor: shape=(1, 1), dtype=int64, numpy=array([[4]])>

### cumprod
Compute the cumulative product of the tensor x along axis.
[a, b, c] --> [a, a * b, a * b * c]


In [34]:
x = tf.constant([[0, 0, 1],
                 [1, 2, 4]])

tf.math.cumprod(x, axis=0)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 1],
       [0, 0, 4]], dtype=int32)>

In [37]:
tf.math.cumprod(x, axis=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [1, 2, 8]], dtype=int32)>

In [39]:
# if exclusive is true the
# item[i] = item[1] * item[2]...*item[i-1]
x = tf.constant([1,2,3,4])
tf.math.cumprod(x, exclusive=True)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 1, 2, 6], dtype=int32)>

cum_x[0] = 1

cum_x[1] = x[0] = 1

cum_x[2] = x[0] * x[1] = 1 * 2 = 2

cum_x[3] = x[0] * x[1] * x[2] = 1 * 2 * 3 = 6

### cumsum
- Similar to cumprod, instead of produce, summation will be performed.
- Compute the cumulative sum of the tensor x along axis.


### divide
element-wise divide

In [45]:
x = [10.,20.]
y = [2, 5]
tf.math.divide(x, y)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([5., 4.], dtype=float32)>

### divide_no_nan
- save divide, return zero in case of zero divisible case

In [46]:
y = [0., 2.]
tf.math.divide_no_nan(x, y)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0., 10.], dtype=float32)>

### equal
- Returns the truth value of (x == y) element-wise.

In [47]:
x = [2. , 3.]
y = [2. , 4.]
tf.math.equal(x, y)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>